
#Here are configs that need reloading to take effect
[initialization]

	[initialization.general]
		#Enable Creative Tab
		creative_tab = true
		#Enables custom Configured config screen
		custom_configured_screen = true
		#Set to false to disable custom dispenser behaviors (i.e: filling jars) if for some reason they are causing trouble
		dispensers = true
		#Creates a creative tab full of filled jars
		jar_tab = false

	[initialization.entities]
		firefly = true

	[initialization.blocks]
		clock_block = false
		speaker_block = false
		sack = true
		#WIP
		laser_block = false
		bellows = false
		hanging_sign = true
		bomb = true
		#WIP
		amethyst_arrow = false
		cage = true
		stone_tile = true
		blaze_rod = true
		bamboo_spikes = false
		hourglass = true
		raked_gravel = true
		jar = true
		stick = true
		rope_arrow = true
		checker_block = false
		slingshot = true
		wattle_and_daub = true
		stone_lamp = false
		cog_block = false
		crank = true
		copper_lantern = true
		pancake = false
		statue = true
		iron_gate = true
		bamboo_spikes_tipped = false
		netherite_trapdoor = true
		fodder = true
		end_stone_lamp = false
		globe = true
		sconce = true
		candelabra = true
		timber_frame = false
		spring_launcher = false
		safe = true
		sconce_lever = true
		#WIP
		present = true
		sign_post = true
		pedestal = true
		blackboard = true
		netherite_door = true
		candle_holder = true
		flint_block = false
		flag = true
		candy = true
		rope = true
		notice_board = false
		redstone_illuminator = false
		crimson_lantern = true
		lock_block = true
		flax = false
		planter = true
		wind_vane = true
		item_shelf = true
		turn_table = true
		faucet = true
		blackstone_lamp = false
		daub = true
		gold_trapdoor = true
		feather_block = true
		deepslate_lamp = true
		magma_cream_block = false
		goblet = true
		sconce_green = false
		flute = true
		pulley_block = true
		gold_door = true
		shulker_shell = false

